Repository MozillaReality/FirefoxReality, pull requests merged in 2018-08, with the labels that each got.

#302 Add BuildConfig.GIT_HASH so that the git hash may be displayed in the settings menu
  app/build.gradle
Labels: enhancement

#326 include `label=browser-firefox-reality` to the query-string of the "Report an issue" URL (fixes #312)
  app/src/main/res/values/non_I10n.xml
Labels: in progress

#323 Added support for stacked sessions
  app/src/common/shared/org/mozilla/vrbrowser/SessionStore.java
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationBarWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/TrayWidget.java
Labels: in progress

#327 'Caps Lock' key should behave like a 'Shift' key does
  app/src/common/shared/org/mozilla/vrbrowser/ui/CustomKeyboardView.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/KeyboardWidget.java
  app/src/main/res/drawable/ic_icon_keyboard_caps.xml
  app/src/main/res/drawable/ic_icon_keyboard_shift_off.xml
  app/src/main/res/drawable/ic_icon_keyboard_shift_on.xml
Labels: in progress

#329 Don't show the volume layer when in WebVR. Fixes #287.
  app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
Labels: in progress

#284 Issue Template: improve formatting and add helpful tips
  issue_template
Labels: enhancement

#170 [CXB-182] New error templates and code refactor
  app/oculusvr/release/output.json
  app/src/common/shared/org/mozilla/vrbrowser/ErrorPages.java
  app/src/common/shared/org/mozilla/vrbrowser/SessionStore.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationBarWidget.java
  app/src/main/assets/html/error.html
  app/src/main/assets/html/error/css/styles.css
  app/src/main/assets/html/error/images/icon-errorpage-secureconnectionfailed.svg
  app/src/main/assets/html/error/images/icon-errorpage-servernotfound.svg
  app/src/main/assets/html/error/images/icon-errorpage-thisconnectionisuntrusted.svg
  app/src/main/assets/html/error/images/icon-errorpage-unabletoconnect.svg
  app/src/main/assets/html/error/netError.xhtml
Labels: in progress

#340 Privacy mode pages
  app/src/main/assets/html/css/styles.css
  app/src/main/assets/html/images/private-browsing.svg
  app/src/main/assets/html/private.html
Labels: in progress

#337 Added support for localizing internal pages
  app/src/common/shared/org/mozilla/vrbrowser/ErrorPages.java
  app/src/common/shared/org/mozilla/vrbrowser/InternalPages.java
  app/src/common/shared/org/mozilla/vrbrowser/SessionStore.java
  app/src/main/assets/html/error/images/icon-errorpage-secureconnectionfailed.svg
  app/src/main/assets/html/error/images/icon-errorpage-servernotfound.svg
  app/src/main/assets/html/error/images/icon-errorpage-thisconnectionisuntrusted.svg
  app/src/main/assets/html/error/images/icon-errorpage-unabletoconnect.svg
  app/src/main/assets/html/error/netError.xhtml
  app/src/main/assets/html/images/private-browsing.svg
  app/src/main/assets/html/private.html
  app/src/main/res/raw/error_pages.html
  app/src/main/res/raw/error_style.css
  app/src/main/res/raw/private_mode.html
  app/src/main/res/raw/private_style.css
  app/src/main/res/values/localpages.xml
Labels: in progress

#345 update Issue Template for better formating of error logs
  issue_template
Labels: in progress

#338 Update icon background size and color
  app/build.gradle
  app/src/main/ic_launcher-web.png
  app/src/main/res/drawable/ffgvr_background.png
  app/src/main/res/drawable/ffgvr_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/ic_launcher_background.xml
  app/src/wavevr/AndroidManifest.xml
  app/src/wavevr/ic_launcher-web.png
  app/src/wavevr/res/mipmap-hdpi/ic_launcher.png
  app/src/wavevr/res/mipmap-mdpi/ic_launcher.png
  app/src/wavevr/res/mipmap-xhdpi/ic_launcher.png
  app/src/wavevr/res/mipmap-xxhdpi/ic_launcher.png
  app/src/wavevr/res/mipmap-xxxhdpi/ic_launcher.png
Labels: in progress

#368 Fix black flicker when widgets are shown. Fixes #367
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
  app/src/common/shared/org/mozilla/vrbrowser/Widget.java
  app/src/common/shared/org/mozilla/vrbrowser/WidgetPlacement.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/BrowserWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/UIWidget.java
  app/src/main/cpp/BrowserWorld.cpp
  app/src/main/cpp/Widget.cpp
  app/src/main/cpp/Widget.h
  app/src/main/cpp/WidgetPlacement.cpp
  app/src/main/cpp/WidgetPlacement.h
Labels: in progress

#372 Implement initial launch splash image. Fixes #332.
  app/CMakeLists.txt
  app/src/main/assets/logo.png
  app/src/main/cpp/BrowserWorld.cpp
  app/src/main/cpp/BrowserWorld.h
  app/src/main/cpp/LoadingAnimation.cpp
  app/src/main/cpp/Quad.cpp
  app/src/main/cpp/Quad.h
  app/src/main/cpp/SplashAnimation.cpp
  app/src/main/cpp/SplashAnimation.h
Labels: in progress

#369 fixes privacy mode page list items alignment
  app/src/main/res/raw/private_style.css
Labels: in progress

#366 Added support for geolocalized search engines
  app/src/common/shared/org/mozilla/vrbrowser/SettingsStore.java
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
  app/src/common/shared/org/mozilla/vrbrowser/search/GeolocationTask.java
  app/src/common/shared/org/mozilla/vrbrowser/search/SearchEngine.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationURLBar.java
  app/src/main/res/values/non_I10n.xml
Labels: in progress

#395 Add telemetry probes for searches are performed. Fixes #364
  app/src/common/shared/org/mozilla/vrbrowser/search/SearchEngine.java
  app/src/common/shared/org/mozilla/vrbrowser/telemetry/TelemetryWrapper.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/KeyboardWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationURLBar.java
Labels: in progress

#396 Use SDK recommended WebVR size on oculus
  app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
Labels: in progress

#403 Compile fix for new onLoadError() GV API
  app/src/common/shared/org/mozilla/vrbrowser/SessionStore.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationBarWidget.java
Labels: in progress

#399 Update Oculus AndroidManifest.xml to support store requirements. Fixes #341
  app/src/main/res/values/styles.xml
  app/src/oculusvrDebug/AndroidManifest.xml
  app/src/oculusvrRelease/AndroidManifest.xml
  build.gradle
Labels: in progress

#391 Developer options panel
  app/src/common/shared/org/mozilla/vrbrowser/SessionStore.java
  app/src/common/shared/org/mozilla/vrbrowser/SettingsStore.java
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
  app/src/common/shared/org/mozilla/vrbrowser/WidgetManagerDelegate.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/BrowserWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/DeveloperOptionsEditText.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/DeveloperOptionsWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/KeyboardWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationBarWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/RestartDialogWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/SettingsButton.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/SettingsWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/TrayWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/UIWidget.java
  app/src/main/cpp/BrowserWorld.cpp
  app/src/main/cpp/BrowserWorld.h
  app/src/main/cpp/VRBrowser.cpp
  app/src/main/cpp/VRBrowser.h
  app/src/main/res/drawable/developer_options_background.xml
  app/src/main/res/drawable/edittext_background.xml
  app/src/main/res/drawable/edittext_textcolor.xml
  app/src/main/res/drawable/ic_settings_developeroptions.xml
  app/src/main/res/drawable/radio.xml
  app/src/main/res/drawable/radio_off.xml
  app/src/main/res/drawable/radio_on.xml
  app/src/main/res/drawable/scrollbar.xml
  app/src/main/res/drawable/settings_background.xml
  app/src/main/res/drawable/switch_thumb.xml
  app/src/main/res/drawable/switch_track.xml
  app/src/main/res/layout/developer_options.xml
  app/src/main/res/layout/restart_dialog.xml
  app/src/main/res/layout/settings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/non_I10n.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: in progress

#404 fix a couple typos in and improve formatting of README
  README.md
Labels: enhancement, in progress

#402 replace Home URL to hosted New-Tab/Feed page (fixes #324)
  app/src/common/shared/org/mozilla/vrbrowser/SessionStore.java
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
  app/src/common/shared/org/mozilla/vrbrowser/search/SearchEngine.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationBarWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationURLBar.java
  app/src/googlevrFlat/java/org/mozilla/vrbrowser/BrowserActivity.java
  app/src/main/assets/html/index.html
  app/src/main/assets/html/logo.png
Labels: in progress

#410 Move the try button down
  app/src/main/res/raw/error_pages.html
Labels: in progress

#411 Fix Oculus WebVR size
  app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
Labels: in progress

#416 Add deadzone when clicking so that buttons are easier to activate
  app/src/main/cpp/BrowserWorld.cpp
  app/src/main/cpp/Controller.cpp
  app/src/main/cpp/Controller.h
Labels: in progress

#346 Make WebVR work with multiprocess enabled
  app/src/main/cpp/ExternalBlitter.cpp
  app/src/main/cpp/ExternalVR.cpp
Labels: in progress

#425 Added url bar clear support
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
  app/src/common/shared/org/mozilla/vrbrowser/WidgetManagerDelegate.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/KeyboardWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationBarWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationURLBar.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/UIWidget.java
  app/src/main/res/drawable/ic_icon_clear.xml
  app/src/main/res/xml/keyboard_qwerty.xml
Labels: in progress

#430 Enable Daydream WebVR swapchain
  app/src/googlevr/cpp/DeviceDelegateGoogleVR.cpp
Labels: in progress

#424 New pointer design
  app/src/googlevr/assets/vr_controller_daydream.mtl
  app/src/googlevr/assets/vr_controller_daydream.obj
  app/src/googlevr/assets/vr_controller_daydream_tex.png
  app/src/main/cpp/BrowserWorld.cpp
  app/src/main/cpp/ControllerContainer.cpp
  app/src/main/cpp/ControllerContainer.h
  app/src/main/cpp/Widget.cpp
  app/src/main/cpp/Widget.h
  app/src/main/res/values/dimen.xml
  app/src/oculusvr/assets/vr_controller_oculusgo.mtl
  app/src/oculusvr/assets/vr_controller_oculusgo.obj
  app/src/oculusvr/assets/vr_controller_oculusgo_tex.png
  app/src/svr/assets/vr_controller_daydream.mtl
  app/src/svr/assets/vr_controller_daydream.obj
  app/src/svr/assets/vr_controller_daydream_tex.png
  app/src/wavevr/assets/vr_controller_focus.mtl
  app/src/wavevr/assets/vr_controller_focus.obj
  app/src/wavevr/assets/vr_controller_focus_tex.png
Labels: in progress

#439 Adjust scroll speed on Oculus
  app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
Labels: in progress

#441 Fix WebVR remote controller names
  app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
  app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp
Labels: in progress

#436 Pause media when the app goes to background.
  app/src/common/shared/org/mozilla/vrbrowser/SessionStore.java
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
Labels: in progress

#445 New Keyboard UI implementation
  app/src/common/shared/org/mozilla/vrbrowser/ui/CustomKeyboard.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/CustomKeyboardView.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/KeyboardWidget.java
  app/src/main/res/drawable/keyboard_button_background.xml
  app/src/main/res/drawable/keyboard_button_icon.xml
  app/src/main/res/drawable/keyboard_featured_key_background.xml
  app/src/main/res/drawable/keyboard_key_background.xml
  app/src/main/res/drawable/keyboard_key_close_background.xml
  app/src/main/res/drawable/keyboard_popupkey_background.xml
  app/src/main/res/drawable/keyboard_popupkey_capend_background.xml
  app/src/main/res/drawable/keyboard_popupkey_capstart_background.xml
  app/src/main/res/drawable/keyboard_popupkey_single_background.xml
  app/src/main/res/layout/keyboard.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/xml/keyboard_popup.xml
  app/src/main/res/xml/keyboard_qwerty.xml
  app/src/main/res/xml/keyboard_symbols.xml
  app/src/main/res/xml/keyboard_symbols2.xml
Labels: in progress

#448 Remove restart requirement from multiprocess setting.
  app/src/common/shared/org/mozilla/vrbrowser/SessionStore.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/DeveloperOptionsWidget.java
Labels: in progress

#449 Switch support for clolorblind
  app/src/common/shared/org/mozilla/vrbrowser/ui/DeveloperOptionsWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/SettingsWidget.java
  app/src/main/res/layout/developer_options.xml
  app/src/main/res/layout/settings.xml
  app/src/main/res/values/strings.xml
Labels: in progress

#450 Enable custom elements preference
  app/src/common/shared/org/mozilla/vrbrowser/SessionStore.java
Labels: in progress

#447 Add 3D spinner loading animation
  app/src/main/assets/Bake.jpg
  app/src/main/assets/spinners_v3.mtl
  app/src/main/assets/spinners_v3.obj
  app/src/main/cpp/BrowserWorld.cpp
  app/src/main/cpp/LoadingAnimation.cpp
Labels: in progress
