Repository MozillaReality/FirefoxReality, pull requests merged in 2018-11, with the labels that each got.

#800 Fix back button for Oculus
  app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
Labels: bug

#857 Catch unhandled URISyntaxException when parsing URLs for UA override. Fixes #848
  app/src/common/shared/org/mozilla/vrbrowser/browser/UserAgentOverride.java
Labels: P1, crash 🔥

#859 update v1.1 strings for "zh-TW" locale (fixes issue #858)
  app/src/main/res/values-es/FirefoxReality_localpages.xml
  app/src/main/res/values-es/FirefoxReality_strings.xml
  app/src/main/res/values-fr/FirefoxReality_localpages.xml
  app/src/main/res/values-it/FirefoxReality_localpages.xml
  app/src/main/res/values-zh-rCN/FirefoxReality_localpages.xml
  app/src/main/res/values-zh-rTW/FirefoxReality_localpages.xml
  app/src/main/res/values-zh-rTW/FirefoxReality_strings.xml
  app/src/main/res/values-zh-rTW/androidcomponents_strings.xml
Labels: L10n
