Repository MozillaReality/FirefoxReality, pull requests merged in 2018-10, with the labels that each got.

#591 Added missing letter to the keyboard
  app/src/main/res/xml/keyboard_qwerty.xml
Labels: in progress

#590 Support intent preferences for benchmarks
  app/src/common/shared/org/mozilla/vrbrowser/SessionStore.java
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
Labels: in progress

#595 Check for a null URI in the TelemertryWrapper when page is stopped.
  app/src/common/shared/org/mozilla/vrbrowser/telemetry/TelemetryWrapper.java
Labels: in progress

#597 Fixed noapi laucher icon
  app/src/noapi/AndroidManifest.xml
Labels: in progress

#601 Update telemetry app name to be FLAVOR_platform.
  app/src/common/shared/org/mozilla/vrbrowser/telemetry/TelemetryWrapper.java
Labels: in progress

#599 Avoid overriding user input in URL bar
  app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationURLBar.java
Labels: in progress

#602 Added a Java global exception handler
  app/src/common/shared/org/mozilla/vrbrowser/CrashReporterService.java
  app/src/common/shared/org/mozilla/vrbrowser/GlobalExceptionHandler.java
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
Labels: in progress

#603 Bump GV version
  build.gradle
Labels: in progress

#607 Refactored Developer Options code
  app/src/common/shared/org/mozilla/vrbrowser/SettingsStore.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/DeveloperOptionsWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/settings/ButtonSetting.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/settings/DoubleEditSetting.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/settings/RadioGroupSetting.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/settings/SingleEditSetting.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/settings/SwitchSetting.java
  app/src/main/res/layout/developer_options.xml
  app/src/main/res/layout/setting_button.xml
  app/src/main/res/layout/setting_edit.xml
  app/src/main/res/layout/setting_radio_group.xml
  app/src/main/res/layout/setting_switch.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/non_L10n.xml
  app/src/main/res/values/settings_values.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: in progress

#609 Fixed focus handling for VoiceSearch
  app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationBarWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationURLBar.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/TopBarWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/TrayWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/UIButton.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/VoiceSearchWidget.java
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/non_L10n.xml
Labels: in progress

#605 Support added for loading local files through file:// handler
  app/src/common/shared/org/mozilla/vrbrowser/PermissionDelegate.java
  app/src/common/shared/org/mozilla/vrbrowser/SessionStore.java
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
  app/src/common/shared/org/mozilla/vrbrowser/WidgetManagerDelegate.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/CrashDialogWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/DeveloperOptionsWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/KeyboardWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/NavigationBarWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/PermissionWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/RestartDialogWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/SettingsWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/TrayWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/UIWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/prompts/ChoicePromptWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/utils/ValueHolder.java
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/strings.xml
Labels: in progress

#637 fix typo in `private_browsing_title` L10n string
  app/src/main/res/values/localpages.xml
Labels: in progress

#633 Adding support for speech library 1.0.5 containing multi-lingual capabilities and the possibility to set a tag do identify the product using the speech API.
  app/build.gradle
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/VoiceSearchWidget.java
Labels: in progress

#626 Add localizations notes to the application strings. Fixes #625 #624
  app/build.gradle
  app/src/common/shared/org/mozilla/vrbrowser/ui/settings/ButtonSetting.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/views/SettingsButton.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/CrashDialogWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/DeveloperOptionsWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/RestartDialogWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/VoiceSearchWidget.java
  app/src/main/res/layout/crash_dialog.xml
  app/src/main/res/layout/developer_options.xml
  app/src/main/res/layout/keyboard.xml
  app/src/main/res/layout/keyboard_microphone.xml
  app/src/main/res/layout/restart_dialog.xml
  app/src/main/res/layout/settings.xml
  app/src/main/res/layout/voice_search_dialog.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/non_L10n.xml
  app/src/main/res/values/settings_values.xml
  app/src/main/res/values/strings.xml
Labels: in progress

#646 Update README.md
  README.md
Labels: in progress

#653 Fix pixelated (cubemap) background
  app/src/main/cpp/BrowserWorld.cpp
Labels: in progress

#632 Only show the servo button for few websites
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/utils/ServoUtils.java
  servo/src/main/java/org/mozilla/servo/ServoWhiteList.java
  servo/src/main/res/values/servo_white_list.xml
Labels: in progress

#658 Update to the latest GV version
  app/src/common/shared/org/mozilla/vrbrowser/browser/SessionStore.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/BrowserWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
  app/src/main/cpp/moz_external_vr.h
  build.gradle
Labels: in progress

#659 Make it obvious to which engine we're switching to
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
  app/src/main/res/drawable/ic_icon_gecko.xml
  app/src/main/res/drawable/ic_icon_servo.png
  app/src/main/res/drawable/ic_icon_servo.xml
  app/src/main/res/layout/navigation_bar.xml
Labels: in progress

#666 Fix not throttled events and errors when pointing the remote on the background.
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/RootWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetManagerDelegate.java
  app/src/main/cpp/BrowserWorld.cpp
Labels: in progress

#660 Simplify onLoadRequest allow or deny code
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
Labels: in progress

#619 Hide home page redirect javascript URLs
  app/src/common/shared/org/mozilla/vrbrowser/browser/SessionStore.java
  app/src/common/shared/org/mozilla/vrbrowser/telemetry/TelemetryWrapper.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java
Labels: in progress

#663 Improve widget depth sorting
  app/src/main/cpp/BrowserWorld.cpp
  app/src/main/cpp/BrowserWorld.h
  app/src/main/cpp/Widget.cpp
  app/src/main/cpp/Widget.h
Labels: in progress

#661 Add strings for video mode
  app/src/main/res/values/strings.xml
Labels: in progress

#656 Add a user property to disable app relaunch on crash
  README.md
  app/build.gradle
  app/src/common/shared/org/mozilla/vrbrowser/crashreporting/CrashReporterService.java
Labels: in progress

#644 Refactored FxR error pages to A-C browser-errorpages component
  app/build.gradle
  app/src/common/shared/org/mozilla/vrbrowser/browser/SessionStore.java
  app/src/common/shared/org/mozilla/vrbrowser/utils/InternalPages.java
  app/src/main/res/values/localpages.xml
  build.gradle
Labels: in progress, v1.1

#662 Improve background dim API
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/CrashDialogWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/DeveloperOptionsWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/PermissionWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/SettingsWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetManagerDelegate.java
  app/src/main/cpp/BrowserWorld.cpp
  app/src/main/cpp/BrowserWorld.h
  app/src/main/cpp/FadeBlitter.cpp
  app/src/main/cpp/FadeBlitter.h
Labels: in progress

#667 add `Bleeding-edge developer APKs` section at top of README
  README.md
Labels: enhancement, in progress
