Repository MozillaReality/FirefoxReality, pull requests merged in 2019-03, with the labels that each got.

#978 Do not allow privatebrowsing page to be bookmarked
  app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
Labels: in progress

#979 Implement dynamic switch between flat and curved display
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetManagerDelegate.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/options/DisplayOptionsWidget.java
  app/src/main/cpp/BrowserWorld.cpp
  app/src/main/cpp/DeviceDelegate.h
  app/src/main/cpp/Widget.cpp
  app/src/main/cpp/Widget.h
  app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
  app/src/oculusvr/cpp/DeviceDelegateOculusVR.h
Labels: in progress

#946 Use real user height on Oculus 6DOF devices
  app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
Labels: in progress

#986 Fix editing only the first field on a DoubleEditSetting
  app/src/common/shared/org/mozilla/vrbrowser/ui/views/settings/DoubleEditSetting.java
Labels: in progress

#992 Update gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: in progress

#991 adjust `User-Agent` override to fix changes to PH
  app/src/main/assets/userAgentOverride.json
Labels: bug, compatibility, in progress

#989 Fixed the second controller doesn't show up problem
  app/src/main/cpp/ControllerContainer.cpp
  app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
Labels: in progress

#998 Bump GeckoView to version 67.0.20190311102806
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
  app/src/common/shared/org/mozilla/vrbrowser/browser/PermissionDelegate.java
  versions.gradle
Labels: in progress

#1003 Fix unexpected forward page actions due to SwipeRight gesture on WaveVR
  app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp
Labels: in progress

#1004 Making Wave support 6DOF controllers.
  app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp
Labels: in progress

#993 Fix setting window size oddities
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/options/DisplayOptionsWidget.java
Labels: in progress

#1002 Discard back button presses to exit the app in WaveVR and Daydream
  app/src/googlevr/java/org/mozilla/vrbrowser/PlatformActivity.java
  app/src/wavevr/java/org/mozilla/vrbrowser/PlatformActivity.java
Labels: in progress

#985 Implement basic auth prompt
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/prompts/AuthPromptWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/prompts/PromptWidget.java
  app/src/main/res/layout/prompt_auth.xml
  app/src/main/res/values/strings.xml
Labels: in progress

#1008 Force IonMonkey on 64 bit builds
  app/src/common/shared/org/mozilla/vrbrowser/browser/SessionStore.java
Labels: in progress

#1012 Fix permission listeners called on the wrong thread
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
Labels: in progress

#981 Replace Gamepad id from "Gear VR Controller" to Oculus Go/HTC HTC Vive Focus controllers
  app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
  app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp
Labels: in progress

#1001 Fix unable to select items in a multi-picklist #953
  app/src/common/shared/org/mozilla/vrbrowser/ui/views/CustomListView.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/prompts/ChoicePromptWidget.java
  app/src/main/res/layout/prompt_choice.xml
  app/src/main/res/values/dimen.xml
Labels: in progress

#1011 Reset keyboard layout when active editable element changes focus
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
Labels: in progress

#1014 Add Island environment
  app/src/main/assets/cubemap/island/negx.ktx
  app/src/main/assets/cubemap/island/negy.ktx
  app/src/main/assets/cubemap/island/negz.ktx
  app/src/main/assets/cubemap/island/posx.ktx
  app/src/main/assets/cubemap/island/posy.ktx
  app/src/main/assets/cubemap/island/posz.ktx
  app/src/main/res/drawable/environment_island.jpg
  app/src/main/res/values/options_values.xml
  app/src/main/res/values/strings.xml
  app/src/uncompressed_assets/main/assets/cubemap/island/negx.jpg
  app/src/uncompressed_assets/main/assets/cubemap/island/negy.jpg
  app/src/uncompressed_assets/main/assets/cubemap/island/negz.jpg
  app/src/uncompressed_assets/main/assets/cubemap/island/posx.jpg
  app/src/uncompressed_assets/main/assets/cubemap/island/posy.jpg
  app/src/uncompressed_assets/main/assets/cubemap/island/posz.jpg
Labels: in progress

#1015 Replace Oculus 6DOF immersive exit btn to Menu btn.
  app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
Labels: in progress

#1023 Correctly hide controller on autoselected VR video playback
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/VideoProjectionMenuWidget.java
Labels: in progress

#996 Add optional audio gesture intent paramenter
  app/src/common/shared/org/mozilla/vrbrowser/browser/SessionStore.java
Labels: in progress

#1030 Fix environment switch glitches
  app/src/main/cpp/Skybox.cpp
Labels: in progress

#1032 Set correct Oculus WebVR device name
  app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
Labels: in progress

#1035 Hide Wave controller if input is captured by system
  app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp
Labels: in progress

#1033 update icons and logos with low-poly versions (fixes issue #1016)
  app/src/debug/res/drawable/ff_logo.png
  app/src/debug/res/drawable/ff_logo_settings.png
  app/src/main/assets/logo.png
  app/src/main/ic_launcher-web.png
  app/src/main/res/drawable/ff_logo.png
  app/src/main/res/drawable/ff_logo_settings.png
  app/src/main/res/drawable/ffgvr_background.png
  app/src/main/res/drawable/ffgvr_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/colors.xml
  app/src/wavevr/ic_launcher-web.png
  app/src/wavevr/res/mipmap-hdpi/ic_launcher.png
  app/src/wavevr/res/mipmap-mdpi/ic_launcher.png
  app/src/wavevr/res/mipmap-xhdpi/ic_launcher.png
  app/src/wavevr/res/mipmap-xxhdpi/ic_launcher.png
  app/src/wavevr/res/mipmap-xxxhdpi/ic_launcher.png
Labels: in progress

#1028 [WIP] Fixes #864: Added Contributing.md
  CONTRIBUTING.md
Labels: in progress

#1039 Do not dim scene brightness when selecting environments
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetManagerDelegate.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/EnvironmentOptionsWidget.java
Labels: in progress

#1036 Set WebVR sitStanding transform. Set WebVR neck model for 3DOF devices.
  app/src/googlevr/cpp/DeviceDelegateGoogleVR.cpp
  app/src/main/cpp/Device.h
  app/src/main/cpp/DeviceDelegate.h
  app/src/main/cpp/ExternalVR.cpp
  app/src/main/cpp/ExternalVR.h
  app/src/main/cpp/moz_external_vr.h
  app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
  app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp
  versions.gradle
Labels: in progress

#960 Blur the edges of UI background shapes
  app/src/main/res/drawable/dialog_background.xml
  app/src/main/res/drawable/edittext_background.xml
  app/src/main/res/drawable/keyboard_background.xml
  app/src/main/res/drawable/main_button.xml
  app/src/main/res/drawable/media_controls_background.xml
  app/src/main/res/drawable/prompt_background.xml
  app/src/main/res/drawable/settings_background.xml
  app/src/main/res/drawable/url_background.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimen.xml
Labels: enhancement, in progress

#1046 Bump GeckoView to version 68.0.20190327044526
  app/src/common/shared/org/mozilla/vrbrowser/browser/SessionStore.java
  versions.gradle
Labels: in progress

#1047 Add Youtube webcompat webextension
  app/src/common/shared/org/mozilla/vrbrowser/browser/SessionStore.java
  app/src/main/assets/web_extensions/youtube_webcompat/main.css
  app/src/main/assets/web_extensions/youtube_webcompat/main.js
  app/src/main/assets/web_extensions/youtube_webcompat/manifest.json
Labels: in progress
