Repository MozillaReality/FirefoxReality, pull requests merged in 2019-07, with the labels that each got.

#1360 Import strings from android-l10n
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: import-l10n

#1370 Import strings from android-l10n
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: import-l10n

#1384 Fix controller state on Daydream devices.
  app/src/googlevr/cpp/DeviceDelegateGoogleVR.cpp
Labels: bug

#1393 Fixes choice prompt crash
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/prompts/ChoicePromptWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/prompts/PromptWidget.java
  app/src/main/res/values/dimen.xml
Labels: P1, crash 🔥

#1409 Import strings from android-l10n
  app/src/main/res/values-it/strings.xml
Labels: import-l10n

#1405 Bump a-c dependency to 4.0.0
  versions.gradle
Labels: task

#1406 Introduce a centralized places.kt which owns storage
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserApplication.java
  app/src/common/shared/org/mozilla/vrbrowser/browser/BookmarksStore.kt
  app/src/common/shared/org/mozilla/vrbrowser/browser/Places.kt
Labels: task

#1436 Clean up build flavor usage and fix JNI native signature
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/DisplayOptionsView.java
  app/src/main/cpp/BrowserWorld.cpp
Labels: task

#1437 Fix java.lang.NullPointerException in checkYoutubeOverride
  app/src/common/shared/org/mozilla/vrbrowser/browser/SessionStore.java
Labels: task

#1445 Fix menu button triggering back button on WAVE with latest SDK
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
Labels: bug, regression
