Repository MozillaReality/FirefoxReality, pull requests merged in 2019-06, with the labels that each got.

#1293 Import strings from android-l10n
  app/src/main/res/values-zh-rTW/strings.xml
Labels: import-l10n

#1272 Pinyin keyboard fixes
  app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/ChinesePinyinKeyboard.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/views/AutoCompletionView.java
  app/src/main/res/drawable/autocompletion_item_active_color.xml
  app/src/main/res/drawable/autocompletion_item_background.xml
  app/src/main/res/drawable/autocompletion_item_background_first.xml
  app/src/main/res/drawable/autocompletion_item_background_last.xml
  app/src/main/res/layout/autocompletion_bar.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/xml/keyboard_qwerty_pinyin.xml
Labels: in progress

#1300 Fixed the Telemetry issues
  app/src/common/shared/org/mozilla/vrbrowser/telemetry/FxRTelemetryScheduler.java
  app/src/common/shared/org/mozilla/vrbrowser/telemetry/TelemetryWrapper.java
Labels: bug, regression

#1301 Adjust controller beam position and orientation to closer match the system (fixes #1291)
  app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp
Labels: task

#1238 support video playback on Vimeo 360 video pages via WebCompat Web Extension (fixes issue #841)
  app/src/common/shared/org/mozilla/vrbrowser/browser/SessionStore.java
  app/src/main/assets/userAgentOverride.json
  app/src/main/assets/web_extensions/webcompat_vimeo/main.css
  app/src/main/assets/web_extensions/webcompat_vimeo/main.js
  app/src/main/assets/web_extensions/webcompat_vimeo/manifest.json
  app/src/main/assets/web_extensions/webcompat_youtube/main.css
  app/src/main/assets/web_extensions/webcompat_youtube/main.js
  app/src/main/assets/web_extensions/webcompat_youtube/manifest.json
Labels: enhancement

#1305 Import strings from android-l10n
  app/src/main/res/values-zh-rCN/strings.xml
Labels: import-l10n

#1308 Ensure every build target is assembled on staging builds of master
  .taskcluster.yml
Labels: task

#1340 Import strings from android-l10n
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: import-l10n
