Repository MozillaReality/FirefoxReality, pull requests merged in 2019-05, with the labels that each got.

#1160 add more debugging tips for Build Variants and recording Oculus videos
  README.md
Labels: documentation

#1167 use consistent typeface in Media Transport Controls, remove "Open Sans" (fixes issue #1166)
  app/src/main/res/layout/media_controls.xml
  app/src/main/res/layout/media_controls_seek_bar.xml
Labels: enhancement

#1177 Add support for resizing alphabetic keyboard with based on language
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/BaseKeyboard.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/KeyboardInterface.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetPlacement.java
  app/src/main/res/layout/keyboard.xml
  app/src/main/res/values/dimen.xml
Labels: UX, enhancement, in progress

#1172 add direct links to bleeding-edge developer APKs for each platform generated from Taskcluster builds
  README.md
Labels: documentation, enhancement

#1199 fix shift key (fixes issue #1188)
  app/src/main/res/drawable/ic_icon_keyboard_caps.xml
  app/src/main/res/drawable/ic_icon_keyboard_shift_off.xml
  app/src/main/res/drawable/ic_icon_keyboard_shift_on.xml
Labels: bug, regression

#1205 Adjust Focus touchpad scroll speed.
  app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp
Labels: P1, UX, enhancement, platform:WaveVR

#1191 Add back button to NoAPI UI
  app/src/main/res/layout/noapi_layout.xml
  app/src/noapi/java/org/mozilla/vrbrowser/PlatformActivity.java
Labels: P2, bug

#1216 fix User-Agent Override list for Delight-VR (fixes issue #1212; related to PR #1213)
  app/src/main/assets/userAgentOverride.json
Labels: bug, compatibility

#1226 Import strings from android-l10n
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: import-l10n

#1217 YouTube improvements: enter 360 VR without having to first click YouTube's Fullscreen button, set automatic 360 Projection on YouTube 360 videos (fixes issue #1215 and issue #1056)
  app/src/main/assets/web_extensions/youtube_webcompat/main.css
  app/src/main/assets/web_extensions/youtube_webcompat/main.js
Labels: compatibility, enhancement, in progress

#1232 Don't disable user control of projection control in auto projection m…
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
Labels: bug, in progress

#1234 Import strings from android-l10n
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-ko/strings.xml
Labels: import-l10n

#1175 Show correct enter key label based on input IME options
  app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/BaseKeyboard.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/KeyboardInterface.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
  app/src/main/res/layout/navigation_url.xml
Labels: bug, in progress

#1237 Bump GV to 68.0.20190517162900 (fixes #786: `Accept-Language` header)
  versions.gradle
Labels: L10n, bug

#1246 Import strings from android-l10n
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ru/strings.xml
Labels: import-l10n

#1250 Import strings from android-l10n
  app/src/main/res/values-zh-rCN/strings.xml
Labels: import-l10n

#1248 remove User-Agent overrides, per latest Delight-VR upgrade (fixes issue #1247)
  app/src/main/assets/userAgentOverride.json
Labels: compatibility, enhancement

#1261 Ensure UA override works for redirects
  app/src/common/shared/org/mozilla/vrbrowser/browser/SessionStore.java
Labels: bug

#1270 Import strings from android-l10n
  app/src/main/res/values-zh-rCN/strings.xml
Labels: import-l10n

#1277 Import strings from android-l10n
  app/src/main/res/values-zh-rCN/strings.xml
Labels: import-l10n

#1278 Update upload_symbols.sh to use new script for finding native lib
  tools/taskcluster/.gitignore
  tools/taskcluster/upload_symbols.sh
Labels: task

#1279 Clean up code warnings
  app/src/main/cpp/BrowserWorld.cpp
  app/src/main/cpp/BrowserWorld.h
  app/src/main/cpp/Cylinder.h
  app/src/main/cpp/Device.h
  app/src/main/cpp/ElbowModel.cpp
  app/src/main/cpp/ElbowModel.h
  app/src/main/cpp/ExternalBlitter.cpp
  app/src/main/cpp/ExternalBlitter.h
  app/src/main/cpp/ExternalVR.cpp
  app/src/main/cpp/ExternalVR.h
  app/src/main/cpp/FadeAnimation.cpp
  app/src/main/cpp/FadeAnimation.h
  app/src/main/cpp/GeckoSurfaceTexture.cpp
  app/src/main/cpp/GestureDelegate.cpp
  app/src/main/cpp/GestureDelegate.h
  app/src/main/cpp/LoadingAnimation.cpp
  app/src/main/cpp/LoadingAnimation.h
  app/src/main/cpp/Pointer.cpp
  app/src/main/cpp/Pointer.h
  app/src/main/cpp/Quad.cpp
  app/src/main/cpp/Quad.h
  app/src/main/cpp/Skybox.cpp
  app/src/main/cpp/Skybox.h
  app/src/main/cpp/SplashAnimation.cpp
  app/src/main/cpp/SplashAnimation.h
  app/src/main/cpp/VRVideo.cpp
  app/src/main/cpp/VRVideo.h
  app/src/main/cpp/Widget.cpp
  app/src/main/cpp/Widget.h
  app/src/main/cpp/WidgetPlacement.h
  app/src/main/cpp/WidgetResizer.cpp
  app/src/main/cpp/WidgetResizer.h
  app/src/noapi/cpp/DeviceDelegateNoAPI.cpp
Labels: task

#1202 Avoid Infinite restart loop in the CrashReporterService
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
  app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java
  app/src/common/shared/org/mozilla/vrbrowser/crashreporting/CrashReporterService.java
  app/src/common/shared/org/mozilla/vrbrowser/crashreporting/GlobalExceptionHandler.java
  app/src/main/res/values/non_L10n.xml
Labels: bug

#1280 Fix Java crash reporter
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
  app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java
  app/src/common/shared/org/mozilla/vrbrowser/crashreporting/CrashReporterService.java
  app/src/common/shared/org/mozilla/vrbrowser/crashreporting/GlobalExceptionHandler.java
  app/src/main/res/values/non_L10n.xml
Labels: bug
