Repository MozillaReality/FirefoxReality, pull requests merged in 2019-11, with the labels that each got.

#2127 Prevent voice search from getting stuck in a cancel loop
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/VoiceSearchWidget.java
Labels: bug, crash 🔥

#2144 Fix crash in onLoadRequest()
  app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java
Labels: bug, crash 🔥

#2361 Prevent setting tracking protection state on suspended Sessions. Fixes #2360
  app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java
Labels: crash 🔥

#2241 Migrate telemetry pings to Glean (Stage 2)
  app/metrics.yaml
  app/pings.yaml
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
  app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java
  app/src/common/shared/org/mozilla/vrbrowser/search/SearchEngineWrapper.java
  app/src/common/shared/org/mozilla/vrbrowser/telemetry/GleanMetricsService.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
  docs/metrics.md
Labels: telemetry
