Repository MozillaReality/FirefoxReality, pull requests merged in 2019-08, with the labels that each got.

#1487 Ensure the vrb::RunnableQueue has been created before the Activiy tries to call it in onCreate()
  app/src/main/cpp/native-lib.cpp
Labels: bug

#1558 Ensure session is create with correct VR UA (fixes #1546)
  app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStack.java
Labels: regression

#1563 Add missing curly brackets to if statements
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
  app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStack.java
  app/src/common/shared/org/mozilla/vrbrowser/input/CustomKeyboard.java
  app/src/common/shared/org/mozilla/vrbrowser/search/suggestions/SuggestionsProvider.java
  app/src/common/shared/org/mozilla/vrbrowser/telemetry/TelemetryWrapper.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/LanguagesAdapter.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/views/CustomKeyboardView.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/views/HoneycombButton.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/views/UIButton.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/views/UITextButton.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/views/VolumeControl.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/MenuWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/SuggestionsWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TopBarWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/UIWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/AppDialogWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/ContextMenuWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/VoiceSearchWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/prompts/AuthPromptWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/prompts/ChoicePromptWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/DisplayLanguageOptionsView.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/DisplayOptionsView.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsFooter.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsHeader.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsView.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/utils/LocaleUtils.java
  app/src/common/shared/org/mozilla/vrbrowser/utils/ViewUtils.java
  app/src/main/cpp/BrowserWorld.cpp
Labels: task

#1574 Add debug logging switch to release build developer options
  app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java
  app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStore.java
  app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionUtils.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/DeveloperOptionsView.java
  app/src/main/res/layout/options_developer.xml
  app/src/main/res/values/non_L10n.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#1566 Prevent crash reporter from getting stuck in an infinte loop
  app/src/common/shared/org/mozilla/vrbrowser/crashreporting/CrashReporterService.java
Labels: bug

#1593 Pin third_party for taskcluster builds
  third_party_hash
  tools/taskcluster/get_third_party.sh
Labels: enhancement, task

#1673 Import strings from android-l10n
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-nb-rNO/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-nn-rNO/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-sv-rSE/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: import-l10n

#1688 Add dontobfuscate option to pro-guard rules. Fixes #1683
  app/proguard-rules.pro
Labels: enhancement
