Repository MozillaReality/FirefoxReality, pull requests merged in 2019-10, with the labels that each got.

#1918 Handle exceptions thrown by java.net.URI
  app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStack.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java
Labels: bug, crash 🔥

#1954 Update taskcluster scripts to support v2 signing
  .taskcluster.yml
  tools/taskcluster/sign_apk.py
Labels: bug

#1878 Add support for Bluetooth keyboards. Fixes #775
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
Labels: enhancement

#2038 Clone WidgetPlacement before sending to VR render thread to prevent concurrent access.
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetPlacement.java
Labels: bug

#2056 Fix long press menu highlight state. Fixes #2047
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/MenuWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/ContextMenuWidget.java
  app/src/main/res/values/strings.xml
Labels: bug

#2053 Fix potential title shown in new tab button when view is reused
  app/src/common/shared/org/mozilla/vrbrowser/ui/views/TabView.java
Labels: bug

#1854 Replace telemetry service with Glean. (Stage 1)
  app/build.gradle
  app/metrics.yaml
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserApplication.java
  app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java
  app/src/common/shared/org/mozilla/vrbrowser/telemetry/GleanMetricsService.java
  docs/metrics.md
  versions.gradle
Labels: telemetry

#2087 Set prompt delegate when new stacked tab is created
  app/src/common/shared/org/mozilla/vrbrowser/browser/PromptDelegate.java
Labels: bug, regression
