Repository MozillaReality/FirefoxReality, pull requests merged in 2019-09, with the labels that each got.

#1769 Import strings from android-l10n
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-ru/strings.xml
Labels: import-l10n

#1699 Update FxR Java logging to include class name in LOGTAG
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
  app/src/common/shared/org/mozilla/vrbrowser/audio/AudioEngine.java
  app/src/common/shared/org/mozilla/vrbrowser/browser/Media.java
  app/src/common/shared/org/mozilla/vrbrowser/browser/PermissionDelegate.java
  app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java
  app/src/common/shared/org/mozilla/vrbrowser/browser/UserAgentOverride.java
  app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStack.java
  app/src/common/shared/org/mozilla/vrbrowser/crashreporting/CrashReporterService.java
  app/src/common/shared/org/mozilla/vrbrowser/crashreporting/GlobalExceptionHandler.java
  app/src/common/shared/org/mozilla/vrbrowser/geolocation/GeolocationData.java
  app/src/common/shared/org/mozilla/vrbrowser/input/MotionEventGenerator.java
  app/src/common/shared/org/mozilla/vrbrowser/telemetry/TelemetryWrapper.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/OffscreenDisplay.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/BookmarkAdapter.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/adapters/HistoryAdapter.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/ChinesePinyinKeyboard.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/ChineseZhuyinKeyboard.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/JapaneseKeyboard.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/views/HistoryView.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/views/HoneycombButton.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/views/NavigationURLBar.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/MediaControlsWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TitleBarWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/UIWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/CrashDialogWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/PermissionWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/RestartDialogWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/VoiceSearchWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/utils/SystemUtils.java
  app/src/googlevr/java/org/mozilla/vrbrowser/PlatformActivity.java
  app/src/noapi/java/org/mozilla/vrbrowser/PlatformActivity.java
  app/src/oculusvr/java/org/mozilla/vrbrowser/PlatformActivity.java
  app/src/svr/java/org/mozilla/vrbrowser/PlatformActivity.java
  app/src/wavevr/java/org/mozilla/vrbrowser/PlatformActivity.java
Labels: enhancement

#1785 Save autoplay state. Fixes #1781
  app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java
  app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStore.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/DisplayOptionsView.java
  app/src/main/res/values/non_L10n.xml
Labels: bug

#1811 Prevent Widgets from being retained by the MotionEventGenerator after a pause. Fixes #1728
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
  app/src/common/shared/org/mozilla/vrbrowser/input/MotionEventGenerator.java
Labels: bug

#1828 Import strings from android-l10n
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
Labels: import-l10n

#1827 Correctly check for IME Action when processing the done key. Fixes #1816
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
Labels: bug

#1835 Remove Window and Max Window Size settings. Fixes #1822
  app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/DisplayOptionsView.java
  app/src/main/res/layout/options_display.xml
  app/src/main/res/layout/setting_edit.xml
  app/src/main/res/values/non_L10n.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#1836 Speculative fixes for keyboard crashes. Fixes #1821
  app/src/common/shared/org/mozilla/vrbrowser/input/CustomKeyboard.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
Labels: bug, crash 🔥

#1845 Fix crash from URI.create unhandled exceptions. Fixes #1844
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TitleBarWidget.java
Labels: bug, crash 🔥

#1848 Clear Navigation Bar focus when window changes focus. Fixes #1841
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
Labels: bug

#1847 Write a file containing the crash files location. Fixes #1846
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
  app/src/common/shared/org/mozilla/vrbrowser/crashreporting/CrashReporterService.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/CrashDialogWidget.java
Labels: bug

#1849 Ensure History and Bookmark labels are shown in url bar when they are visible. Fixes #1818
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
Labels: bug

#1861 Disable WebRender until it works with FxR
  app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionUtils.java
Labels: bug

#1867 Remove most 32bit builds from taskcluster builds. Fixes #1855
  tools/taskcluster/build_targets.py
Labels: enhancement

#1868 Check both height and width of border for change in length. Fixes #1851
  app/src/main/cpp/Widget.cpp
Labels: bug

#1869 Import strings from android-l10n
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es-rES/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-nb-rNO/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sv-rSE/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
Labels: import-l10n

#1881 Import strings from android-l10n
  app/src/main/res/values-fr/strings.xml
Labels: import-l10n

#1888 Disable 32 bit builds for pull requests
  .taskcluster.yml
Labels: enhancement

#1889 Add support for feature branch builds on taskcluster
  .taskcluster.yml
  tools/taskcluster/sign_apk.py
Labels: enhancement

#1894 Import strings from android-l10n
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
Labels: import-l10n
