Repository MozillaReality/FirefoxReality, pull requests merged in 2019-04, with the labels that each got.

#790 Add support for UI texture scaling
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TrayWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WidgetPlacement.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
  app/src/main/cpp/BrowserWorld.cpp
  app/src/main/cpp/Widget.cpp
  app/src/main/cpp/WidgetPlacement.cpp
  app/src/main/cpp/WidgetPlacement.h
Labels: in progress

#1052 improve default playback quality of YouTube videos to 1440p (or `vq=`, `quality=` query-string parameter) (fixes issue #1051)
  app/src/common/shared/org/mozilla/vrbrowser/browser/SessionStore.java
  app/src/main/assets/web_extensions/youtube_webcompat/main.css
  app/src/main/assets/web_extensions/youtube_webcompat/main.js
  app/src/main/assets/web_extensions/youtube_webcompat/manifest.json
Labels: compatibility, in progress

#1087 Always dump combined proguard ruels to build/outputs/mapping/configuation.txt
  app/proguard-rules.pro
Labels: bug, in progress

#1090 L10n review fixes.
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/options/DeveloperOptionsWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/options/PrivacyOptionsWidget.java
  app/src/main/res/layout/options_privacy.xml
  app/src/main/res/values/strings.xml
Labels: L10n, in progress

#1091 update icon for "Controller Options" in Settings
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/SettingsWidget.java
  app/src/main/res/drawable/ic_settings_controlleroptions_oculusvr_3dof.xml
  app/src/main/res/drawable/ic_settings_controlleroptions_oculusvr_6dof.xml
  app/src/main/res/drawable/ic_settings_environment.xml
  app/src/main/res/layout/settings.xml
Labels: enhancement

#1106 fix interpolation symbol in L10n strings for Video Seeking (fixes issue #1105)
  app/src/main/res/values/strings.xml
Labels: bug

#1128 Import strings from android-l10n
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values-zh-rTW/strings.xml
  l10n.toml
Labels: L10n, import-l10n
