Repository MozillaReality/FirefoxReality, pull requests merged in 2020-03, with the labels that each got.

#2867 Use the default appservices megazord, not the deprecated fenix megazord.
  app/build.gradle
  versions.gradle
Labels: QA

#2936 Dual controller typing
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
  app/src/common/shared/org/mozilla/vrbrowser/input/MotionEventGenerator.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/views/CustomKeyboardView.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Widget.java
  app/src/main/cpp/BrowserWorld.cpp
  app/src/main/cpp/ControllerContainer.cpp
  app/src/main/cpp/VRBrowser.cpp
  app/src/main/cpp/VRBrowser.h
  app/src/main/res/layout/autocompletion_bar.xml
  app/src/main/res/layout/keyboard.xml
Labels: QA

#2975 Only check device if it exists
  app/src/common/shared/org/mozilla/vrbrowser/input/MotionEventGenerator.java
Labels: crash 🔥

#2980 Handle version code conversion in debug builds
  app/src/common/shared/org/mozilla/vrbrowser/utils/StringUtils.java
Labels: crash 🔥

#2959 Pico Gaze Mode support
  app/src/main/cpp/BrowserWorld.cpp
  app/src/main/cpp/ControllerContainer.cpp
  app/src/main/cpp/ControllerContainer.h
  app/src/main/cpp/ControllerDelegate.h
  app/src/main/cpp/DeviceDelegate.h
  app/src/main/cpp/ExternalVR.cpp
  app/src/picovr/cpp/DeviceDelegatePicoVR.cpp
  app/src/picovr/cpp/DeviceDelegatePicoVR.h
  app/src/picovr/cpp/VRBrowserPico.cpp
  app/src/picovr/cpp/VRBrowserPico.h
  app/src/picovr/java/org/mozilla/vrbrowser/PlatformActivity.java
Labels: QA

#3010 Prevent crash when only one controller has moved
  app/src/common/shared/org/mozilla/vrbrowser/input/MotionEventGenerator.java
Labels: crash 🔥

#3005 Update signing script to print server error to log
  tools/taskcluster/sign_apk.py
Labels: enhancement

#3079 Disable layers for oculus runtime 1.1.32.0
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
  app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java
  app/src/main/cpp/VRBrowser.cpp
  app/src/main/cpp/VRBrowser.h
  app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
  app/src/oculusvr/java/org/mozilla/vrbrowser/PlatformActivity.java
Labels: crash 🔥
