Repository MozillaReality/FirefoxReality, pull requests merged in 2020-07, with the labels that each got.

#3613 Convert LEFT to Left in Neo 2 left controller name
  app/src/picovr/cpp/DeviceDelegatePicoVR.cpp
Labels: Uplift

#3602 Fixes Thai alphabetic cap keyboard switch
  app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/BaseKeyboard.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/KeyboardInterface.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
  app/src/main/res/xml/keyboard_qwerty_thai.xml
  app/src/main/res/xml/keyboard_symbols_thai.xml
Labels: Uplift

#3629 Fixes #3620 Fixes #3634 Fix private session restore crash
  app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java
Labels: Uplift

#3618 Fixes #3605 Link FxA login flow to the originating session
  app/src/common/shared/org/mozilla/vrbrowser/browser/Accounts.kt
  app/src/common/shared/org/mozilla/vrbrowser/ui/views/library/BookmarksView.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/views/library/HistoryView.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/WhatsNewWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsWidget.java
Labels: Uplift

#3621 Fixes #3617 Disable reload button in private mode
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
Labels: Uplift

#3630 Fixes #3623 Avoid releasing the voice search widget on config changes
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
Labels: Uplift

#3614 Fixes #3607 Fixes #3606 What's new fixes
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
Labels: Uplift

#3635 Replace Thai quotation with semicolon.
  app/src/main/res/xml/keyboard_symbols_thai.xml
Labels: Uplift

#3622 Fixes #3591 Support for media controls live language update
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/MediaControlsWidget.java
Labels: Uplift

#3631 Add comment for the web search string parameter
  app/src/main/res/values/strings.xml
Labels: import-l10n

#3639 Fixes #3637 Null check the alphabetic Caps Keyboard when switching shift
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
Labels: Uplift

#3644 Fixes #3643 Telemetry crash fix
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserApplication.java
  app/src/common/shared/org/mozilla/vrbrowser/utils/SystemUtils.java
  app/src/test/java/org/mozilla/vrbrowser/EnvironmentsTest.kt
  app/src/test/java/org/mozilla/vrbrowser/GleanMetricsServiceTest.kt
  app/src/test/java/org/mozilla/vrbrowser/TestApplication.kt
Labels: Uplift

#3654 Assert that vrPrefsWorkAround method is called before creating the Gecko Runtime
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserApplication.java
  app/src/common/shared/org/mozilla/vrbrowser/browser/engine/EngineProvider.kt
  app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStore.java
  app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionUtils.java
Labels: Uplift

#3653 Lazily initialize GeckoWebExecutor
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserApplication.java
  app/src/common/shared/org/mozilla/vrbrowser/browser/engine/EngineProvider.kt
  app/src/common/shared/org/mozilla/vrbrowser/browser/engine/GeckoViewFetchClient.kt
Labels: Uplift

#3664 Bump GV to 80.0.20200709093347
  versions.gradle
Labels: Uplift

#3666 Fix 180 equirect layer transform
  app/src/main/cpp/VRVideo.cpp
Labels: Uplift

#3663 Fixes #3658 FxA login signin fix
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/TabsWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
Labels: Uplift

#3667 Fixes #3659 Refresh send tab on configuration changed
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/ClearHistoryDialogWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/dialogs/SendTabDialogWidget.java
Labels: Uplift

#3668 Ensure suspended sessions are not readded to a-c SessionStore
  app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java
Labels: Uplift

#3633 Update supported languages strings comment to reflect all uses
  app/src/common/shared/org/mozilla/vrbrowser/utils/LocaleUtils.java
  app/src/main/res/values/strings.xml
Labels: import-l10n

#3673 Bump GV to 80.0.20200713095122
  versions.gradle
Labels: Uplift

#3669 Fixes #3671 BrowserState-SessionStore sync
  app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java
  app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStore.java
Labels: Uplift

#3682 Do not call addSession in SessionStore.onStackSession()
  app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStore.java
Labels: Uplift

#3683 Fix the unlinking/removing sessions order
  app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java
Labels: Uplift

#3691 Fix RegisterExternalContext() life cycle issues on WaveVR
  app/src/wavevr/cpp/native-lib.cpp
Labels: Uplift

#3703 Fix PicoVR store builds for Neo2
  app/build.gradle
Labels: Uplift, crash 🔥

#3695 Move WaveVR render initialization to a separate method
  app/src/wavevr/cpp/DeviceDelegateWaveVR.cpp
  app/src/wavevr/cpp/DeviceDelegateWaveVR.h
  app/src/wavevr/cpp/native-lib.cpp
Labels: Uplift

#3729 Check resizer before using.
  app/src/main/cpp/Widget.cpp
Labels: crash 🔥
