Repository MozillaReality/FirefoxReality, pull requests merged in 2020-06, with the labels that each got.

#3467 Legacy telemetry data review.
  app/metrics.yaml
  docs/metrics.md
Labels: telemetry

#3430 Multiple window and immersive mode time measurement telemetry.
  app/metrics.yaml
  app/pings.yaml
  app/src/common/shared/org/mozilla/vrbrowser/browser/Places.kt
  app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java
  app/src/common/shared/org/mozilla/vrbrowser/telemetry/GleanMetricsService.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/NavigationBarWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/Windows.java
  app/src/test/java/org/mozilla/vrbrowser/GleanMetricsServiceTest.kt
  docs/metrics.md
  versions.gradle
Labels: telemetry

#3507 Avoid showing Zh-TW and Zh-CN keyboard candidate view when typing symbols.
  app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/ChinesePinyinKeyboard.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/keyboards/ChineseZhuyinKeyboard.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/KeyboardWidget.java
Labels: QA

#3498 Closes #2267 AC WebExtensions + WebCompat + FxAWebChannels
  app/aars/appcompat.aar
  app/build.gradle
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserActivity.java
  app/src/common/shared/org/mozilla/vrbrowser/VRBrowserApplication.java
  app/src/common/shared/org/mozilla/vrbrowser/browser/Services.kt
  app/src/common/shared/org/mozilla/vrbrowser/browser/SessionChangeListener.java
  app/src/common/shared/org/mozilla/vrbrowser/browser/SettingsStore.java
  app/src/common/shared/org/mozilla/vrbrowser/browser/adapter/ComponentsAdapter.kt
  app/src/common/shared/org/mozilla/vrbrowser/browser/components/GeckoEngineSession.kt
  app/src/common/shared/org/mozilla/vrbrowser/browser/components/GeckoResult.kt
  app/src/common/shared/org/mozilla/vrbrowser/browser/components/GeckoWebExtension.kt
  app/src/common/shared/org/mozilla/vrbrowser/browser/components/GeckoWebExtensionRuntime.kt
  app/src/common/shared/org/mozilla/vrbrowser/browser/engine/EngineProvider.kt
  app/src/common/shared/org/mozilla/vrbrowser/browser/engine/Session.java
  app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionState.java
  app/src/common/shared/org/mozilla/vrbrowser/browser/engine/SessionStore.java
  app/src/common/shared/org/mozilla/vrbrowser/browser/extensions/BuiltinExtension.java
  app/src/common/shared/org/mozilla/vrbrowser/telemetry/GleanMetricsService.java
  app/src/common/shared/org/mozilla/vrbrowser/telemetry/TelemetryWrapper.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/settings/SettingsWidget.java
  app/src/common/shared/org/mozilla/vrbrowser/utils/SystemUtils.java
  app/src/main/assets/extensions/fxr_vimeo/main.css
  app/src/main/assets/extensions/fxr_vimeo/main.js
  app/src/main/assets/extensions/fxr_vimeo/manifest.json
  app/src/main/assets/extensions/fxr_youtube/background.js
  app/src/main/assets/extensions/fxr_youtube/main.css
  app/src/main/assets/extensions/fxr_youtube/main.js
  app/src/main/assets/extensions/fxr_youtube/manifest.json
  app/src/test/java/org/mozilla/vrbrowser/GleanMetricsServiceTest.kt
  versions.gradle
Labels: QA

#3585 Fixes #3495 Catch all exceptions when starting an external activity
  app/src/common/shared/org/mozilla/vrbrowser/ui/widgets/WindowWidget.java
Labels: Uplift

#3587 Fix Pico G2 controller touchpad in immersive mode
  app/src/picovr/cpp/DeviceDelegatePicoVR.cpp
Labels: Uplift
